# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TicketLiquidator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TicketLiquidator

  target 'TicketLiquidatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TicketLiquidatorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
